import type { Metadata } from "next";
import { Header } from "@/components/header"
import { Providers } from "./providers"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased dark">
                <Providers>
                    <div className="flex min-h-svh flex-col">
                        <Header />
                        {children}
                    </div>
                </Providers>
            </body>
    </html>
  );
}
